#
# docker compose up -d --build
# docker compose down
# docker exec -it rabbitmq sh
#
# management: http://localhost:15672/ (user&password from .env)
#
# cookie path: /var/lib/rabbitmq/
#
version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
      - ${RABBITMQ_PORT}:5672

networks:
  app:
